[package]
name = "rsensors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
lm-sensors = "0.1.6"
pad = "0.1.6"
pancurses = "0.17"
